---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: careqrapp-service
spec:
 selector:
   matchLabels:
     run: careqrapp-service
 replicas: 1
 template:
   metadata:
     labels:
       run: careqrapp-service
   spec:
     containers:
     - name: careqrapp-service
       image: mijaka/mijaka_pub  
       ports:
       - containerPort: 5173
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
...
