---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: careqrapp-service-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: careqrapp-service
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
...
